### ISSUE TITLE
npm install error after a clean checkout

### ISSUE THREAD

**Issue by naartjie** [reasonml/ReasonProject#14]
Running `npm install` on a clean checkout (bff8722), and I get the following:

```
> ReasonProject@0.0.1 reasonBuild /Users/marchi/Project/Sandbox/reason/ReasonProject
> eval $(dependencyEnv) && nopam && rebuild -use-ocamlfind -cflag -w -cflag -40 -I src ./src/Test.native 2>&1 | refmterr

sh: refmterr: command not found
```

I tried with node `6.9.4` npm `3.10.10`, and node `7.4.0` and npm `4.0.5`. I am on a OS X `10.11.6`

Am I doing something wrong?

**Comment by naartjie** [comment]
I am using `zsh` so I also tried it with `bash` and did a `npm cache clean` before, but the same error.

**Comment by jordwalke** [comment]
This is fixed in master now. What version of reason was resolved?

**Comment by naartjie** [comment]
Confirmed, I got a successful build with latest 0cb66f2. Thanks @jordwalke.
